CocInstall coc-clangd
CocInstall coc-docker
CocInstall coc-git
CocInstall coc-go
CocInstall coc-html
CocInstall coc-htmldjango
CocInstall coc-htmlhint
CocInstall coc-java
CocInstall coc-json
CocInstall coc-markdownlint
CocInstall coc-pyright
CocInstall coc-rome
CocInstall coc-rust-analyzer
CocInstall coc-sh
CocInstall coc-sql
CocInstall coc-sqlfluff
CocInstall coc-sumneko-lua
CocInstall coc-swagger
CocInstall coc-vimlsp
CocInstall coc-xml
CocInstall coc-yaml
CocInstall coc-tsserver
