#!/bin/bash

alias cdf='cd ~/forge'
alias cda='cd ~/forge/all-repos'
alias cdt='cd ~/forge/todo'
alias cdr='cd ~/repos'
alias cdw='cd ~/workspaces'

alias watch='watch --color'
alias todo='nvim ~/forge/todo/tasks.md'

alias fcdf='cdf && cd'
alias fcda='cda && cd'

alias python='python3'
alias vim='nvim'
alias vi='nvim'

# Remove all colour from the command line
alias remove-colour="sed 's/\x1b\[[0-9;]*m//g'"

alias shrug='echo "¯\_(ツ)_/¯"'
alias give='echo "༼ つ ◕_◕ ༽つ"'

