#!/bin/bash

CONFIGROOT_DIR_SCRIPT="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" >/dev/null 2>&1 && git rev-parse --show-toplevel 2>/dev/null || echo ~/.vim )"
## Use untracked-sourced-scripts to symlink directories that you want to source scripts from, but you don't want to track in git
if [[ -d "${CONFIGROOT_DIR_SCRIPT}/system-configs/rcfiles/untracked-sourced-scripts" ]]; then
  for untracked_sourced_scripts_dir in "${CONFIGROOT_DIR_SCRIPT}/system-configs/rcfiles/untracked-sourced-scripts/"*; do
    if [[ -d "${untracked_sourced_scripts_dir}" ]]; then
      # shellcheck disable=SC1090
      for script in "${untracked_sourced_scripts_dir}/"*; do
        if [[ -f ${script} ]]; then
          # shellcheck disable=SC1090
          source "${script}"
        fi
      done
    fi
  done
fi 
